export const projects = [{
        id: 1,
        title: 'Freedom',
        type: 'Mobile App',
        progress: '36%',
        chats: 12,
        color: 'purple',
        members: ['def', 'free1', 'free2'],
        due_date: '1-09-2021',
    },
    {
        id: 2,
        title: 'Apparent',
        type: 'Web App',
        progress: '96%',
        chats: 3,
        color: 'orange',
        members: ['def', 'app1'],
        due_date: '1-09-2021',
    },
    {
        id: 3,
        title: 'Notes',
        type: 'Mobile App',
        progress: '6%',
        chats: 0,
        color: 'deepOrange',
        members: ['def'],
        due_date: '1-09-2021',
    },
    {
        id: 4,
        title: 'stayKE',
        type: 'Web App',
        progress: '59%',
        chats: 7,
        color: 'brown',
        members: ['def', 'person1', '2erson2', '3persom'],
        due_date: '1-09-2021',
    },
];

export const tasks = [{
        id: 1,
        title: 'Make site responsive',
        status: 0,
        due_date: '1-09-2021',
        project_id: 2,
        assigned: null,
        tags: [],
    },
    {
        id: 2,
        title: 'Creating a responsive version of the site',
        status: 1,
        due_date: '1-09-2021',
        project_id: 2,
        assigned: null,
        tags: [],
    },
    {
        id: 3,
        title: 'todo3',
        status: 2,
        due_date: '1-09-2021',
        project_id: 2,
        assigned: null,
        tags: [],
    },
    {
        id: 4,
        title: 'todo 4',
        status: 0,
        due_date: '1-09-2021',
        project_id: 3,
        assigned: null,
        tags: [],
    },
];